[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
verion_four = "BjJ49YJZLpvgb4ckbs25fz8Zfq1gEzsWMneTur7pwss7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
